stages:
  - validate
  - plan
  - apply
  - sync-k8s-cluster

image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  TF_ROOT: ./staging  # The relative path to the root directory of the Terraform project
  PLAN: plan.cache
  PLAN_JSON: plan.json
  KUBE_CONFIG: kube.config
  ARGOCD_USERNAME: "admin"
  ARGOCD_PASSWORD: "argoAdmin"
  ARGOCD_USER_MV: "argo"
  ARGOCD_PASSWORD_MV: "argo"
  ARGOCD_HOST: "10.63.27.54"
  ARGOCD_PORT: 30580

before_script:
  - rm -rf .terraform
  - terraform --version
  - cd "${TF_ROOT}"
  - terraform init

cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/

validate:
  stage: validate
  tags:
    - ic2m2
  script:
    - terraform validate

plan:
  stage: plan
  tags:
    - ic2m2
  script:
    - terraform plan -out=$PLAN
    - terraform show -no-color -json $PLAN > $PLAN_JSON
  dependencies:
    - validate
  artifacts:
    paths:
      - ${TF_ROOT}/$PLAN
      - ${TF_ROOT}/$PLAN_JSON

apply:
  stage: apply
  tags:
    - ic2m2
  script:
    - terraform apply -auto-approve
  dependencies:
    - plan

sync-k8s-cluster:
  stage: sync-k8s-cluster
  tags:
    - ic2m2
  script:
    - ssh -i keys/key-file ubuntu:10.63.27.69 microk8s config > $KUBE_CONFIG
    - sshpass -p "$ARGOCD_PASSWORD_MV" ssh -o StrictHostKeyChecking=no $ARGOCD_USER_MV@$ARGOCD_HOST "argocd login $ARGOCD_HOST:$ARGOCD_PORT --insecure --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD && argocd cluster add microk8s-cluster --kubeconfig $KUBE_CONFIG"

