stages:
  - validate
  - plan
  - apply

image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  TF_ROOT: ./staging  # The relative path to the root directory of the Terraform project
  PLAN: plan.cache
  PLAN_JSON: plan.json
  KUBE_CONFIG: kube.config

before_script:
  - rm -rf .terraform
  - terraform --version
  - cd "${TF_ROOT}"
  - terraform init

cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/

validate:
  stage: validate
  tags:
    - ic2m2
  script:
    - terraform validate

plan:
  stage: plan
  tags:
    - ic2m2
  script:
    - terraform plan -out=$PLAN
    - terraform show -no-color -json $PLAN > $PLAN_JSON
  dependencies:
    - validate
  artifacts:
    paths:
      - ${TF_ROOT}/$PLAN
      - ${TF_ROOT}/$PLAN_JSON

apply:
  stage: apply
  tags:
    - ic2m2
  script:
    - terraform apply -auto-approve
  dependencies:
    - plan

sync-k8s-cluster:
  stage: sync-k8s-cluster
  tags:
    - ic2m2
  script:
    - curl -L https://tuf.werf.io/targets/releases/1.2.269/linux-amd64/bin/werf -o werf
    - chmod +x werf
    - mv werf /usr/local/bin/werf
    - microk8s config > $KUBE_CONFIG
    - werf argocd cluster add microk8s-cluster --kubeconfig $KUBE_CONFIG
