include:
  #- local: 'development/.gitlab-ci.yml'
  - local: 'staging/.gitlab-ci.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == "master"
        when: always
  - local: 'production/.gitlab-ci.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == "master"
        when: always
