stages:
  - trigger-staging
  - trigger-production

trigger-staging:
  stage: trigger-staging
  trigger:
    include: staging/.gitlab-ci.yml

trigger-production:
  stage: trigger-production
  trigger:
    include: production/.gitlab-ci.yml
